name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fossas/fossa-action@v1
      with:
        api-key: ${{secrets.fossaApiKey}}
    - uses: fossas/fossa-action@v1
      with:
        api-key: ${{secrets.fossaApiKey}}
        run-tests: true
    - uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: yarn install --frozen-lockfile
    - run: yarn test
